version: '3'

services:

  seymour:
    build:
      context: docker/seymour
    command: php-fpm
    expose:
      - "9000"
    volumes:
      - ./:/var/www:cached

  nginx:
    build:
      context: docker/nginx
    # command: ['nginx-debug']
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www:cached
    depends_on:
      - seymour
    networks:
      default:
        aliases:
          - seymour.test

  node:
    build:
      context: docker/node
    volumes:
      - ./:/var/www:cached
