<?php

namespace App\Feeds;

use App\Feeds\Simulator;

abstract class FakeFeed {

    /**
     * @var Simulator
     */
    public $simulator;

    /**
     * Create a new FakeFeed instance.
     *
     * @param Simulator $simulator
     * @return void
     */
    public function __construct(Simulator $simulator)
    {
        $this->simulator = $simulator;
    }

    /**
     * Retrieve the feed url generated by the simulator.
     *
     * @return string
     */
    public function getUrl(): string
    {
        return $this->simulator->linkToFeed;
    }

    /**
     * Convert this fake feed to a string.
     *
     * @return string
     */
    public function toString(): string
    {
        return (string)$this;
    }

    /**
     * Create a string representation of this fake feed.
     *
     * @return string
     */
    abstract public function __toString(): string;

    /**
     * Create a string representation of an entry in this fake feed.
     *
     * @param array $entry
     * @return string
     */
    abstract protected function entryToString(array $entry): string;

    /**
     * What type of feed variant does this class represent?
     *
     * @return string
     */
    abstract public function type(): string;
}
