name: CI

on: [pull_request]

jobs:

  phpunit:
    runs-on: ubuntu-latest
    container:
      image: stagerightlabs/php-test-runner:8.0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer Dependency Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os}}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer install --no-scripts --no-ansi --no-progress

      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install NPM Dependencies
        run: npm install --no-progress

      - name: Run NPM Asset Pipeline
        run: |
          npm run build:js
          npm run build:css

      - name: Prepare Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run PHP Test Suite
        run: ./vendor/bin/phpunit
